import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "public/redux/StoreProvider";
import Header from "@/components/Header";
import ScrollToTop from "@/components/ScrollToTop";
import FooterParent from "@/components/FooterParent";
import ClientProvider from "@/components/ClientProvider";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "پدربزرگ",
  description: "Generated by create next app",
  icons: {
    icon: "/Image/favicon.ico",
  },
};

const fetchFunc = async (par: any) => {
  const res = await fetch(`${process.env.API}/core-api/user/customers/me/`, {
    method: "GET",
    credentials: 'include',
    headers: {
      Authorization: `JWT ${par}`
    }
  })
  return res.json()
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookiesStore = cookies()
  const accessToken = cookiesStore.get("access")
  const refreshToken = cookiesStore.get("refresh")

  const me = accessToken && await fetchFunc(accessToken?.value)

  return (
    <html lang="fa" className='bg-base-100 overflow-x-hidden'>
      <body>
        <StoreProvider>
          <ClientProvider token={{ accessToken, refreshToken }} me={me}>
            <Header />
            <ScrollToTop />
            {children}
            <FooterParent />
          </ClientProvider>
        </StoreProvider>
      </body>
    </html >
  );
}
