import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "public/redux/StoreProvider";
import Header from "@/components/Header";
import ScrollToTop from "@/components/ScrollToTop";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "پدربزرگ",
  description: "Generated by create next app",
  icons: {
    icon: "/Image/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="fa" className='bg-base-100 overflow-x-hidden'>
      <body>
        <StoreProvider>
          <Header />
          <ScrollToTop />
          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html >
  );
}
